<TRANSCRIBE>:
  - 转录如下音频。
  - 转录这段音频中的语音内容为文字。
  - 将音频的语音部分转换为文字形式，谢谢。
  - 将这段音频的语音内容详细记录为文字稿。
  - 执行语音识别任务，将音频转换为文字。
<TRANSCRIBE> <ALIGN>:
  - 请将以下音频进行转录，同时标记出每个英文单词及对应中文字符的起始与结束时间，时间单位精确到0.1秒，并用<>来表示这些时间范围。
  - 转录音频内容，并为每个英文词汇及其对应的中文翻译标注出精确到0.1秒的起止时间，时间范围用<>括起来。
  - 将音频转录为文字，同时在每个英文单词和相应中文字符的前后添加时间戳，时间戳格式为<>，且时间单位需精确到0.1秒。
  - 请将音频转化为文字记录，并标记每个英文词及其对应中文的起始时间和结束时间，时间单位至少为0.1秒，使用<>来标注这些时间。
  - 将音频内容进行转录处理，并为其中的每个英文单词及其翻译后的中文标注时间范围，时间精确到0.1秒，并用<>进行包围。


<TRANSCRIBE> <S2TCHAT>:
 - 首先将语音转录为文字，然后对语音内容进行回复，转录和文字之间使用<开始回答>分割。
 - 首先将语音转换为文本，接着使用<开始回答>作为分隔，最后对语音内容进行回复。
 - 首先把语音变成文本，然后用<开始回答>作分隔，最后对语音内容予以回应。
 - 首先将语音转化为书面语，随后以<开始回答>作分隔，最后对语音内容做出答复。
 - 首先将语音转为文字形式，之后用<开始回答>来分隔，最后对语音内容给予回应。


<TRANSCRIBE> <EMOTION>:
  - 请将以下音频内容进行转录，并在结尾处给出<情感>标签，情感共分为8类：sad，anger，neutral，happy，surprise，fear，disgust，以及other。
  - 将音频转录为文字，并在文本最后附加<情感>标签，标签类型涵盖：sad，anger，neutral，happy，surprise，fear，disgust，还有other。
  - 请将音频内容转录成文字记录，并在记录末尾标注<情感>标签，情感共8种：sad，anger，neutral，happy，surprise，fear，disgust，和other。
  - 将音频进行文字化处理，并在处理后的文本末尾添加<情感>标签，标签种类有8种：sad，anger，neutral，happy，surprise，fear，disgust，以及其他情况other。
  - 请将音频转录成文，并在文末给出<情感>标签，情感分为八大类：sad，anger，neutral，happy，surprise，fear，disgust，以及不属于上述类别的other。


<TRANSCRIBE> <STYLE>:
  - 请将以下音频内容进行转录，并在结尾处给出<风格>标签，风格共分为8类：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。
  - 将音频转录为文字，并在文本末尾附加<风格>标签，标签种类包括：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。
  - 将音频内容进行文字转录，并在最后添加<风格>标签，标签共8种：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。
  - 将音频转录为文字记录，并在记录末尾附上<风格>标签，风格共8类，分别是：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。
  - 将音频内容转录成文，并在文末标注<风格>标签，风格分类有8种，即：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。



<TRANSCRIBE> <CAPTION>:
  - 请将以下音频进行转录，并在结尾处给出<音频事件>标签，音频事件分为8类：laugh，cough，cry，screaming，sigh，throat clearing，sneeze，other。
  - 将音频内容转录成文字，并在文本最后附上<音频事件>标签，标签类型包括：laugh，cough，cry，screaming，sigh，throat clearing，sneeze以及other。
  - 请将音频转录为文字记录，并在记录末尾标注<音频事件>标签，音频事件共8种：laugh，cough，cry，screaming，sigh，throat clearing，sneeze，other。
  - 将音频内容进行文字化处理，并在处理后的文本末尾添加<音频事件>标签，标签种类有8种：laugh，cough，cry，screaming，sigh，throat clearing，sneeze，other。
  - 请将音频转录成文，并在文末给出<音频事件>标签，音频事件分为八大类：laugh，cough，cry，screaming，sigh，throat clearing，sneeze以及其他情况other。


<TRANSCRIBE> <GENDER>:
  - 请将这段音频进行转录，并在文本末尾附加<性别>标签。性别分为两种：female，male。
  - 请将音频内容转录成文字，并在最后加上<性别>标签，标明是female还是male。
  - 请将音频转录为文本，并在文本结尾处标注<性别>标签，性别为female或male。
  - 请将音频进行文字转录，并在转录文本的末尾附上<性别>标签，标签内容为female或male。
  - 请将音频内容转换为文字，并在文字末尾添加<性别>标签，以指示是female还是male。



<TRANSCRIBE> <AGE>:
  - 将这段音频进行转录，并在转录完成的文本末尾附加<年龄>标签。年龄类别分为三种：child、adult、old。
  - 请将以下音频内容转录成文字，并在文字的最后加上<年龄>标签，标明是child、adult还是old。
  - 将音频转录为文本，并在文本结尾处标注<年龄>标签，年龄划分为child、adult和old三种。
  - 请将音频进行详细的文字转录，并在转录文本的末尾附上<年龄>标签，标签内容为child、adult或old。
  - 将音频内容转换成文字形式，并在转换后的文字末尾添加<年龄>标签，用以指示是child、adult还是old的年龄阶段。





<TRANSCRIBE> <AGE> <GENDER>:
  - 请将这段音频进行转录，并在转录完成的文本末尾附加"<年龄> <性别>"标签。年龄分为child、adult、old三种，性别为female或male。
  - 请将以下音频内容转录成文字，并在文字的最后加上"<年龄> <性别>"标签，标明是child、adult或old，以及female或male。
  - 请将音频转录为文本，并在文本结尾处标注"<年龄> <性别>"标签，年龄划分为child、adult和old，性别分为female和male。
  - 请将音频进行详细的文字转录，并在转录文本的末尾附上"<年龄> <性别>"标签，标签内容为child、adult或old，以及female或male的性别标识。
  - 请将音频内容转换成文字形式，并在转换后的文字末尾添加"<年龄> <性别>"标签，用以指示说话者的年龄阶段（child、adult、old）以及性别（female、male）。

<AGE> <GENDER>:
  - 请识别以下音频发言者的年龄和性别。年龄分为child、adult、old三种，性别为MALE和FEMALE。
  - 请识别以下音频中的说话者的年龄和性别。年龄分为child、adult、old三种，性别为MALE和FEMALE。
  - 请判断下列音频中的发言者的年龄与性别。年龄层次为child、adult、old，性别为MALE和FEMALE。
  - 请确定以下音频中讲话人的年龄和性别。年龄可分为child、adult、old三个阶段，性别为MALE和FEMALE。
  - 请分析下列音频中的说话人的年龄和性别。年龄划分为child、adult、old三类，性别为MALE和FEMALE。



#<SOT>: 暂时不再提供该功能。
#  - 请依据说话人的先后顺序转录以下音频，使用<sc>标签分隔不同说话人的内容。
#  - 请把下列音频按说话人出现的顺序转录，并在不同说话人的内容间插入<sc>标签。
#  - 请将音频中的话语按说话人先进先出的原则转录，并用<sc>标签区分不同说话人的抄本。
#  - 请按照说话人的出场顺序转录以下音频，使用<sc>标签来分隔不同说话人的部分。
#  - 请根据说话人的先后顺序将以下音频转录，不同说话人的内容之间请用<sc>标签进行分隔。



<TRANSCRIBE> <STYLE> <AGE> <GENDER>:
  - 请将以下音频内容进行转录，并在转录完成的文本末尾分别附加<风格>、<年龄>、<性别>标签。风格共分为8类：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄分为child、adult、old三种，性别为MALE和FEMALE。
  - 请将下列音频内容进行转录，并在转录文本的末尾分别添加<风格>、<年龄>、<性别>标签。风格有8类：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄划分为child、adult、old三种，性别分为MALE和FEMALE。
  - 请转录以下音频内容，并在转录后的文本末尾标注<风格>、<年龄>、<性别>标签。风格包括新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他8种类型。年龄分为child、adult、old，性别则为MALE和FEMALE。
  - 请将以下音频内容转录，并在转录完成后，附加<风格>、<年龄>、<性别>三个标签。风格一共有8种，包括新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄层次分为child、adult、old，性别为MALE和FEMALE。
  - 请对以下音频内容进行转录，并在文本结尾分别添加<风格>、<年龄>、<性别>标签。风格有8种类型：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄划分为child、adult、old三个阶段，性别则为MALE和FEMALE。

<STYLE> <AGE> <GENDER>:
  - 请识别如下音频的说话风格、说话者的年龄和性别。其中风格有8种类型：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄划分为child、adult、old三个阶段，性别则为MALE和FEMALE。
  - 请分析以下音频的说话风格、说话者的年龄和性别。风格包括8种类型：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄划分为child、adult、old三个层次，性别为MALE和FEMALE。
  - 请识别下面音频的说话风格、说话者的年龄和性别。风格分为8种类型：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄段分为child、adult、old三类，性别为MALE和FEMALE。
  - 请对以下音频进行分析，识别说话风格、说话者年龄和性别。风格类型有8种，包括新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄阶段为child、adult、old三种，性别为MALE或FEMALE。
  - 请对下面音频内容识别说话风格、说话者的年龄和性别。风格包括8个类别：新闻科普、恐怖故事、童话故事、客服、诗歌散文、有声书、日常口语、其他。年龄分为child、adult、old三个阶段，性别为MALE或FEMALE。

